### ISSUE TITLE
6.Load Expense Data from XML

### ISSUE THREAD

**Issue by minkas-g-d** [SoftUniTeamVolta/Supermarkets-Chain-#4]
1. Create an XML file holding expenses by vendor and month.
2. Create new tables and relationships to keep the expenses by period in your SQL Server database.
3. Write a C# program to read the XML file, parse it and save the data in the SQL Server database.

**Input:** XML file holding expenses by vendors by months.
**Output:** program for loading an XML expense report in SQL Server; data loaded in the SQL Server database.

**Comment by danielpetrovaliev** [comment]
Completed. :)
